-- <YOUR_PROJECT_WORKSPACE>\langchain4j-oracle
-- OracleEmbeddingStore

-- *** TBC - TEST AGAIN ***
-- OPENAI WITH gpt-4o MODEL + text-embedding-3-small EMBEDDINGS
CREATE TABLE VECTOR_USER.ORACLE_VECTOR_STORE (ID VARCHAR2(64) PRIMARY KEY, METADATA VARCHAR(256), CONTENT CLOB, VECTOR_DATA VECTOR(1536, FLOAT64));
COMMIT;

DESCRIBE VECTOR_USER.ORACLE_VECTOR_STORE;

SELECT COUNT(*) FROM VECTOR_USER.ORACLE_VECTOR_STORE;

SELECT * FROM VECTOR_USER.ORACLE_VECTOR_STORE;

DELETE FROM VECTOR_USER.ORACLE_VECTOR_STORE;
COMMIT;

DROP TABLE VECTOR_USER.ORACLE_VECTOR_STORE;
COMMIT;

CREATE TABLE documents (
  id RAW(16),
  text CLOB,
  embeddings VECTOR(768, FLOAT32)
);




select
    gvs."DOC_ID",
    gvs."EMBEDDING",
    gvs."ID",
    gvs."METADATA",
    gvs."NODE_INFO",
    gvs."SYS_IME_OSON_3E4C386F069846FFAD7C2D91CFA8D320",
    gvs."SYS_IME_OSON_82C1E0993B824FF2A17D0EDBC10C9077",
    gvs."TEXT"
from
    "GITHUB_VECTOR_STORE" gvs;